"""
integrations.py — Post-generation delivery integrations.

1. Email delivery (SMTP) — send the filled PDF to agent or listing agent
2. Webhook/Zapier — POST structured offer data to any URL
3. DocuSign — create envelope and send for signature via DocuSign eSignature API
"""
import os
import json
import smtplib
import urllib.request
import urllib.error
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import sqlite3

DB_PATH = os.environ.get("DATABASE_PATH", "subscriptions.db")

# --- Email delivery --------------------------------------------------------

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
FROM_EMAIL = os.environ.get("FROM_EMAIL", "offers@txtanoffer.com")


def send_offer_email(to_email: str, pdf_path: str, parsed: dict) -> dict:
    if not SMTP_USER or not SMTP_PASS:
        return {"success": False, "error": "Email not configured (SMTP_USER/SMTP_PASS missing)"}

    msg = MIMEMultipart()
    msg["From"] = FROM_EMAIL
    msg["To"] = to_email
    msg["Subject"] = f"Purchase Offer - {parsed.get('address', 'New Offer')}"

    body = (
        f"Your TREC 20-19 purchase offer is attached.\n\n"
        f"Property: {parsed.get('address', 'N/A')}\n"
        f"Price: ${parsed.get('price', 0):,}\n"
        f"Close: {parsed.get('close_days', 'N/A')} days\n\n"
        f"This is a draft — review all fields before signing.\n\n"
        f"Generated by TxtAnOffer\n"
        f"txtanoffer.com"
    )
    msg.attach(MIMEText(body, "plain"))

    with open(pdf_path, "rb") as f:
        part = MIMEBase("application", "pdf")
        part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = os.path.basename(pdf_path)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)

    try:
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)
        server.quit()
        return {"success": True}
    except Exception as e:
        return {"success": False, "error": str(e)}


# --- Webhook / Zapier ------------------------------------------------------

def _init_webhooks_table():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS webhooks (
            source_id TEXT PRIMARY KEY,
            url TEXT NOT NULL,
            active INTEGER DEFAULT 1
        )
    """)
    conn.commit()
    conn.close()

_init_webhooks_table()


def get_webhook(source_id: str):
    conn = sqlite3.connect(DB_PATH)
    row = conn.execute(
        "SELECT url FROM webhooks WHERE source_id = ? AND active = 1", (source_id,)
    ).fetchone()
    conn.close()
    return row[0] if row else None


def save_webhook(source_id: str, url: str):
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT INTO webhooks (source_id, url) VALUES (?, ?)
        ON CONFLICT(source_id) DO UPDATE SET url=excluded.url, active=1
    """, (source_id, url))
    conn.commit()
    conn.close()


def delete_webhook(source_id: str):
    conn = sqlite3.connect(DB_PATH)
    conn.execute("UPDATE webhooks SET active=0 WHERE source_id = ?", (source_id,))
    conn.commit()
    conn.close()


def fire_webhook(source_id: str, parsed: dict, pdf_url: str) -> dict:
    url = get_webhook(source_id)
    if not url:
        return {"fired": False, "reason": "no_webhook_configured"}

    payload = {
        "event": "offer_generated",
        "address": parsed.get("address", ""),
        "price": parsed.get("price", 0),
        "down_payment_pct": parsed.get("down_payment_pct", 0),
        "down_payment_amount": parsed.get("down_payment_amount", 0),
        "loan_amount": parsed.get("loan_amount", 0),
        "earnest_money": parsed.get("earnest_money", 0),
        "option_fee": parsed.get("option_fee", 0),
        "close_days": parsed.get("close_days", 0),
        "bed": parsed.get("bed"),
        "bath": parsed.get("bath"),
        "sqft": parsed.get("sqft"),
        "pdf_url": pdf_url,
        "agent_phone": source_id,
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return {"fired": True, "status": resp.status}
    except urllib.error.HTTPError as e:
        return {"fired": True, "status": e.code, "error": str(e)}
    except Exception as e:
        return {"fired": False, "error": str(e)}


# --- DocuSign eSignature ---------------------------------------------------

DOCUSIGN_BASE_URL = os.environ.get("DOCUSIGN_BASE_URL", "https://demo.docusign.net/restapi")
DOCUSIGN_ACCOUNT_ID = os.environ.get("DOCUSIGN_ACCOUNT_ID", "")
DOCUSIGN_ACCESS_TOKEN = os.environ.get("DOCUSIGN_ACCESS_TOKEN", "")


def send_to_docusign(pdf_path: str, parsed: dict, signer_email: str, signer_name: str) -> dict:
    if not DOCUSIGN_ACCESS_TOKEN or not DOCUSIGN_ACCOUNT_ID:
        return {"success": False, "error": "DocuSign not configured (DOCUSIGN_ACCESS_TOKEN/DOCUSIGN_ACCOUNT_ID missing)"}

    import base64

    with open(pdf_path, "rb") as f:
        pdf_bytes = base64.b64encode(f.read()).decode("utf-8")

    envelope = {
        "emailSubject": f"Purchase Offer for {parsed.get('address', 'Property')} - Please Review & Sign",
        "documents": [{
            "documentBase64": pdf_bytes,
            "name": f"TREC_20-19_{parsed.get('address', 'offer').replace(' ', '_')}.pdf",
            "fileExtension": "pdf",
            "documentId": "1",
        }],
        "recipients": {
            "signers": [{
                "email": signer_email,
                "name": signer_name,
                "recipientId": "1",
                "routingOrder": "1",
            }]
        },
        "status": "sent",
    }

    url = f"{DOCUSIGN_BASE_URL}/v2.1/accounts/{DOCUSIGN_ACCOUNT_ID}/envelopes"
    data = json.dumps(envelope).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {DOCUSIGN_ACCESS_TOKEN}",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            return {
                "success": True,
                "envelope_id": result.get("envelopeId"),
                "status": result.get("status"),
            }
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8") if e.fp else ""
        return {"success": False, "error": f"DocuSign API error {e.code}: {body[:200]}"}
    except Exception as e:
        return {"success": False, "error": str(e)}
