"""
pdf_filler.py — fills TREC No. 20-19 (One to Four Family Residential
Contract, Resale) using its real AcroForm fields.
Correction from earlier attempts: the draft copy (20-19_draft_0.pdf,
with visible redlines) reported ZERO fillable fields, so we built a
coordinate-overlay approach. The clean, final published PDF
(20-19_2.pdf) actually HAS 281 real AcroForm fields. Field-based
filling is far more robust than coordinate overlay -- it doesn't break
if TREC nudges spacing in a future revision -- so we use that instead.
Field names below were confirmed by inspecting 20-19_2.pdf directly
(inspect_fields() at the bottom of this file reproduces that check).
TREC's PDF export tool auto-names fields from nearby text, which is
why some are verbose ("Texas known as") and some are generic
("undefined_3") -- that's TREC's export, not a choice we made.
"""
import os
import io
from datetime import datetime, timedelta
from pypdf import PdfReader, PdfWriter
from cover_page import generate_cover_page, generate_certification_page
from water_disclosure import fill_water_disclosure
from financing_addendum import fill_financing_addendum
from iabs import fill_iabs
from hoa_addendum import fill_hoa_addendum

TEMPLATE_PATH = os.environ.get("TREC_TEMPLATE_PATH", "20-19_2.pdf")
OUTPUT_DIR = os.environ.get("OFFER_OUTPUT_DIR", "generated_offers")

# Bump this on any change to FIELD_MAP, the overlay coordinates, or the
# merge/namespacing logic -- it's stamped on every generated PDF (footer +
# document metadata) and logged with the offer so that if a bug is found
# later, affected contracts can be identified by which version made them.
GENERATOR_VERSION = "2026-08-17.4"

# Confirmed against 20-19_2.pdf (the clean, final, mandatory-as-of-7/1/2026 form).
# Field names are auto-generated by TREC's PDF tool, so they're verbose.
FIELD_MAP = {
    # Paragraph 1 PARTIES -- never auto-filled by design (this app never
    # collects buyer/seller legal names; the agent fills these by hand
    # before signing, same as their signatures). Named here only so
    # pdf_validator.py can warn when they're still blank at send time.
    "seller_name": "1 PARTIES The parties to this contract are",
    "buyer_name": "Seller and",

    # Paragraph 2A: Property description
    "address": "Texas known as",
    "city": "Addition City of",
    "county": "County of",

    # Page headers — "Contract Concerning (Address of Property)"
    "addr_of_prop": "Addr of Prop",
    "addr_of_prop_p9": "Address of Property",
    "addr_of_prop_p12": "Address of Property_26",
    "addr_header_p2": "Page 2 of 10",
    "addr_header_p3": "Page 3 of 10",
    "addr_header_p4": "Contract Concerning",
    "addr_header_p5": "Contract Concerning_2",
    "addr_header_p6": "Contract Concerning_3",
    "addr_header_p7": "Page 7 of 10",
    "addr_header_p8": "Contract Concerning_4",

    # Paragraph 9A: Closing date
    "closing_date": "A The closing of the sale will be on or before",
    "closing_year_suffix": "20_2",  # The 2-digit year suffix field (form pre-prints "20")

    # Payment structure (Paragraph 3)
    # TREC 20-19 has: 3A (cash portion), 3B (sum of financing), 3C (total sales price)
    # We map: down payment → 3A, loan → 3B, total → 3C
    "down_payment": "undefined_3",  # 3A: Cash portion (down payment)
    "loan_amount": "undefined_4",   # 3B: Sum of all financing
    "sales_price": "undefined_5",   # 3C: Sales Price (total)

    # Earnest Money, Option Fee & Escrow Agent name (Paragraph 5A).
    # NOTE: another instance of TREC's field names lying about their on-page
    # position -- verified by rendering distinct test values into every
    # candidate field on this section and rect-matching against the printed
    # "deliver to ___ (Escrow Agent) at"/"$___ as earnest money"/"$___ as the
    # option fee" text (see git history). The field literally named "earnest
    # money of" is actually 5A(1)'s ADDITIONAL earnest money blank (a later,
    # separately-negotiated amount this app doesn't collect) -- NOT the main
    # earnest money amount. "Option Fee in the form of" isn't even on this
    # page: it's the OPTION FEE RECEIPT block's payment-method blank on the
    # final page, meant to be filled by the escrow agent once funds actually
    # arrive. And the field named "Escrow Agent" is that same receipts page's
    # signature-name blank -- pre-filling it would misrepresent funds as
    # already received before the contract is even sent.
    "earnest_money_amount": "as earnest money to",   # true: 5A "$___ as earnest money"
    "option_fee_amount": "as earnest money to 2",     # true: 5A "$___ as the option fee"
    "escrow_agent_name": "undefined_6",                # true: 5A "deliver to ___ (Escrow Agent) at"

    # Title company (Paragraph 6A) -- separate from escrow agent above.
    "title_company": "insurance Title Policy issued by",

    # Checkboxes
    # NOTE: like financing_addendum.py's Section 1 checkboxes, several of TREC's
    # auto-named fields on this form don't match their on-page position -- their
    # /T text describes a DIFFERENT checkbox/blank than the one they're actually
    # drawn over. Verified by cross-checking each field's /Rect against the
    # actual printed text at that position (see git history for the extraction).
    # Mapped by verified position below, not by trusting the field name text.
    "third_party_financing_3b": "B Sum of all financing described in the attached",  # Para 3B checkbox row
    "third_party_financing": "Addendum for Reservation of Oil Gas",  # true label: "Third Party Financing Addendum" (Sec 22) -- named field is actually the VA Entitlement Release box
    "hoa_addendum": "Check Box9",  # Sec 22 addenda list: "Addendum for Property Subject to Mandatory Membership in a Property Owners Association" -- rect-verified 2026-08-24, on-state /Yes (not /On)
    "as_is": "1 Buyer accepts the Property As Is",
    "possession_upon_closing": "upon",

    # Selling (buyer's) agent info — the TextAnOffer user.
    # Page 11 "BROKER CONTACT INFORMATION" repeats the same labels 3x (Seller's
    # broker / Buyer's broker / Intermediary) and TREC's export shifted every
    # field's /T name by roughly one label -- verified by matching each field's
    # /Rect to the nearest same-column label. These map into the "represents
    # Buyer only as Buyer's agent" block specifically.
    "agent_broker_firm": "Associates Email Address",          # true: Buyer broker firm name
    "agent_name": "Licensed Supervisor of Associate",         # true: Buyer associate's name
    "agent_license": "Phone_2",                                # true: Buyer associate's license no.
    "agent_phone": "Other Brokers Address",                    # true: Buyer associate's phone no.
    "agent_email": "License No_6",                              # true: Buyer associate's email
    "agent_address_broker_contact": "Listing Associates Email Address",  # true: Buyer broker's business Address (page 11)

    # Paragraph 21 NOTICES, "To Buyer's agent at:" block (page 8) -- verified by
    # rendering distinct test values into each field and rect-matching against
    # the printed "Address:"/"Phone:"/"Email:" labels (see git history).
    "agent_address_p21": "when mailed to handdelivered at or transmitted by fax or electronic transmission as follows",
    "agent_address_p21_line2": "at",
    "agent_phone_p21": "Phone 52",
    "agent_email_p21": "undefined_20",
}


def _checkbox_on_state(annot) -> str:
    """The real 'checked' appearance-state name for this checkbox widget,
    read from its own /AP/N dictionary rather than assumed. See the
    checkbox-filling loop below for why this matters."""
    ap = annot.get("/AP")
    if ap and "/N" in ap:
        n_obj = ap["/N"].get_object()
        if hasattr(n_obj, "keys"):
            states = [k for k in n_obj.keys() if k != "/Off"]
            if states:
                return states[0]
    return "/On"


def fill_offer_pdf(parsed: dict, agent_phone: str) -> str:
    if not os.path.exists(TEMPLATE_PATH):
        raise FileNotFoundError(
            f"Template not found at {TEMPLATE_PATH}. "
            "Set TREC_TEMPLATE_PATH to the clean, final 20-19 PDF."
        )
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    reader = PdfReader(TEMPLATE_PATH)
    writer = PdfWriter()
    writer.append(reader)
    
    values = {}

    import re

    # Property description (Paragraph 2A)
    # Strip state from address — the form field already says "Texas, known as"
    addr = ""
    if parsed.get("address"):
        addr = re.sub(r',?\s*\b(TX|Texas)\b', '', parsed["address"], flags=re.IGNORECASE).strip(' ,')
        values[FIELD_MAP["address"]] = addr
    if parsed.get("city"):
        values[FIELD_MAP["city"]] = parsed["city"]
    if parsed.get("county"):
        values[FIELD_MAP["county"]] = parsed["county"]

    # Page header: "Contract Concerning (Address of Property)" on all pages
    city = parsed.get("city", "")
    if city and city.lower() not in addr.lower():
        full_addr = f"{addr}, {city}, TX"
    elif city:
        full_addr = f"{addr}, TX"
    else:
        full_addr = addr
    if full_addr:
        for key in ("addr_of_prop", "addr_of_prop_p9", "addr_of_prop_p12",
                    "addr_header_p2", "addr_header_p3", "addr_header_p4",
                    "addr_header_p5", "addr_header_p6", "addr_header_p7",
                    "addr_header_p8"):
            values[FIELD_MAP[key]] = full_addr

    # Payment structure (Paragraph 3: A, B, C)
    if parsed.get("down_payment_amount") is not None:
        values[FIELD_MAP["down_payment"]] = f"${parsed['down_payment_amount']:,}"
    # 3B (financing sum) stays genuinely blank for an all-cash offer
    # (loan_amount == 0) rather than printing "$0" -- there's no financing
    # to describe, and the checkbox below is correspondingly left unchecked.
    if parsed.get("loan_amount"):
        values[FIELD_MAP["loan_amount"]] = f"${parsed['loan_amount']:,}"
    if parsed.get("price") is not None:
        values[FIELD_MAP["sales_price"]] = f"${parsed['price']:,}"

    # Checkboxes handled separately (need /AS and /V set to /On)
    checkboxes_to_check = []

    # Check Third Party Financing when there's a loan (Para 3B row + Sec 22 addenda list)
    if parsed.get("loan_amount") and parsed["loan_amount"] > 0:
        checkboxes_to_check.append(FIELD_MAP["third_party_financing_3b"])
        checkboxes_to_check.append(FIELD_MAP["third_party_financing"])

    # Check the HOA addendum box in the Sec 22 addenda list whenever the
    # addendum itself is being attached (see fill_hoa_addendum() below).
    if parsed.get("has_hoa"):
        checkboxes_to_check.append(FIELD_MAP["hoa_addendum"])

    # Default: Buyer accepts Property As Is + possession upon closing
    checkboxes_to_check.append(FIELD_MAP["as_is"])
    checkboxes_to_check.append(FIELD_MAP["possession_upon_closing"])

    # Earnest Money & Option Fee (Paragraph 5A)
    if parsed.get("earnest_money") is not None:
        values[FIELD_MAP["earnest_money_amount"]] = f"${parsed['earnest_money']:,}"
    if parsed.get("option_fee") is not None:
        values[FIELD_MAP["option_fee_amount"]] = f"${parsed['option_fee']:,}"

    # Closing date (Paragraph 9A) — handled via reportlab overlay after merge
    # (form field is a parent/kid that doesn't render reliably)

    # Agent/broker info from profile (Buyer's-agent block only — see FIELD_MAP note above)
    agent = parsed.get("agent", {})
    if agent.get("name"):
        values[FIELD_MAP["agent_name"]] = agent["name"]
    if agent.get("license"):
        values[FIELD_MAP["agent_license"]] = agent["license"]
    if agent.get("brokerage"):
        values[FIELD_MAP["agent_broker_firm"]] = agent["brokerage"]
    if agent.get("phone"):
        values[FIELD_MAP["agent_phone"]] = agent["phone"]
    if agent.get("email"):
        values[FIELD_MAP["agent_email"]] = agent["email"]
    if agent.get("business_address"):
        values[FIELD_MAP["agent_address_broker_contact"]] = agent["business_address"]

    # Paragraph 21 NOTICES, "To Buyer's agent at:" block -- same agent info,
    # reused here since TREC repeats the contact block a second time.
    if agent.get("business_address"):
        addr_line1, _, addr_line2 = agent["business_address"].partition(",")
        values[FIELD_MAP["agent_address_p21"]] = addr_line1.strip()
        values[FIELD_MAP["agent_address_p21_line2"]] = addr_line2.strip()
    if agent.get("phone"):
        values[FIELD_MAP["agent_phone_p21"]] = agent["phone"]
    if agent.get("email"):
        values[FIELD_MAP["agent_email_p21"]] = agent["email"]

    # Title company → title policy issuer (Para 6A) + escrow agent name (Para 5A).
    # Does NOT touch the final RECEIPTS page -- those are the escrow agent's
    # own signature blocks acknowledging funds actually received, not
    # something to pre-fill before the contract is even sent.
    if agent.get("title_company"):
        values[FIELD_MAP["title_company"]] = agent["title_company"]
        values[FIELD_MAP["escrow_agent_name"]] = agent["title_company"]
    
    from pypdf.generic import NameObject, TextStringObject, BooleanObject

    for page in writer.pages:
        writer.update_page_form_field_values(page, values)

    # Handle parent fields with /Kids (closing date) — these can't be filled via
    # update_page_form_field_values because the kid widgets have no /T field.
    # Instead, overlay text directly on the page using reportlab.
    acroform = writer._root_object.get("/AcroForm")
    if hasattr(acroform, 'get_object'):
        acroform = acroform.get_object()

    # Check checkboxes by setting /V and /AS to the box's OWN real on-state
    # name, not a hardcoded "/On" -- most of this form's checkboxes use
    # "/On", but at least one (40-11's Buyer Approval, found 2026-08-18)
    # uses "/Yes" instead. Setting /AS to a name that isn't actually a key
    # in the widget's own /AP/N dictionary means no appearance gets painted
    # at all: /V still says checked, but nothing renders, in any viewer that
    # (correctly, per spec) doesn't fall back to guessing intent. Confirmed
    # via Safari, which does not guess -- PyMuPDF's renderer does, which is
    # why this looked fine in every render done during this app's own
    # testing and only showed up once a real listing agent's browser saw it.
    for page in writer.pages:
        if "/Annots" not in page:
            continue
        for annot_ref in page["/Annots"]:
            annot = annot_ref.get_object()
            name = str(annot.get("/T", ""))
            if name in checkboxes_to_check:
                on_state = _checkbox_on_state(annot)
                annot[NameObject("/V")] = NameObject(on_state)
                annot[NameObject("/AS")] = NameObject(on_state)

    # Ensure filled values render even if the PDF viewer doesn't regenerate appearances.
    if acroform is not None:
        acroform[NameObject("/NeedAppearances")] = BooleanObject(True)

    # Write filled TREC form to buffer (preserves AcroForm with field values)
    trec_buf = io.BytesIO()
    writer.write(trec_buf)
    trec_buf.seek(0)

    # Generate premium cover page (light/print mode: these sit next to white
    # TREC forms and get printed for sellers, brokers, and title companies)
    cover_pdf_bytes = generate_cover_page(parsed, parsed.get('agent', {}), mode="light")

    # Generate financing addendum if there's a loan
    financing_pdf_bytes = None
    if parsed.get("loan_amount") and parsed["loan_amount"] > 0:
        financing_pdf_bytes = fill_financing_addendum(parsed)

    # Merge: cover page first, then filled TREC form, then financing addendum
    final_writer = PdfWriter()
    final_writer.append(PdfReader(io.BytesIO(cover_pdf_bytes)))
    final_writer.append(PdfReader(trec_buf))
    if financing_pdf_bytes:
        final_writer.append(PdfReader(io.BytesIO(financing_pdf_bytes)))

    # Closing date: remove the empty kid annotations that cover overlay text, then stamp text
    # Page 6 in final PDF = cover(0) + TREC pages 0-4(1-5) → TREC page 5 = index 6
    if parsed.get("close_days") is not None:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas as rl_canvas
        from pypdf.generic import ArrayObject

        close_dt = datetime.now() + timedelta(days=parsed["close_days"])
        close_text = close_dt.strftime("%B %d,")
        year_suffix = close_dt.strftime("%y")

        target_page = final_writer.pages[6]

        # Remove the closing date and year kid annotations so they don't obscure overlay
        if "/Annots" in target_page:
            annots = target_page["/Annots"]
            keep = []
            for annot_ref in annots:
                annot = annot_ref.get_object()
                rect = annot.get("/Rect")
                if rect:
                    y_bottom = float(rect[1])
                    x_left = float(rect[0])
                    # Both kids are at y~667.6: closing date at x~291, year at x~442
                    if 665 < y_bottom < 680 and (289 < x_left < 295 or 440 < x_left < 445):
                        continue  # skip these annotations
                keep.append(annot_ref)
            target_page[NameObject("/Annots")] = ArrayObject(keep)

        # Draw text directly on page
        overlay_buf = io.BytesIO()
        c = rl_canvas.Canvas(overlay_buf, pagesize=letter)
        c.setFont("Helvetica", 10)
        # Closing date "August 14,": centered in rect [291, 668, 422, 678]
        c.drawString(310, 669, close_text)
        # Year suffix "26": in rect [442, 668, 469, 678]
        c.drawString(448, 669, year_suffix)
        c.save()
        overlay_buf.seek(0)

        overlay_page = PdfReader(overlay_buf).pages[0]
        target_page.merge_page(overlay_page)

    # Page 11 header (Address of Property_2 kid) — overlay like closing date
    # TREC page 10 = final PDF page 11 (index 11) after cover page prepend
    if full_addr:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas as rl_canvas
        from pypdf.generic import ArrayObject

        addr_page = final_writer.pages[11]

        # Remove the kid annotation so it doesn't obscure overlay
        if "/Annots" in addr_page:
            annots = addr_page["/Annots"]
            keep = []
            for annot_ref in annots:
                annot = annot_ref.get_object()
                rect = annot.get("/Rect")
                if rect:
                    y_bottom = float(rect[1])
                    x_left = float(rect[0])
                    # Kid at Rect [126.913, 748.88, 452.753, 764.48]
                    if 746 < y_bottom < 752 and 124 < x_left < 130:
                        continue
                keep.append(annot_ref)
            addr_page[NameObject("/Annots")] = ArrayObject(keep)

        overlay_buf = io.BytesIO()
        c = rl_canvas.Canvas(overlay_buf, pagesize=letter)
        c.setFont("Helvetica", 10)
        # Draw in the rect area [126.913, 748.88, 452.753, 764.48]
        c.drawString(130, 751, full_addr)
        c.save()
        overlay_buf.seek(0)

        overlay_page = PdfReader(overlay_buf).pages[0]
        addr_page.merge_page(overlay_page)

    # Option Period ("Buyer's unrestricted right to terminate... within ___
    # days after the Effective Date") -- Paragraph 5B on TREC page 2. This
    # blank has no AcroForm field at all (not even a broken /Kids one like
    # closing date had) -- confirmed by inspecting every annotation on the
    # page, none sit in that area. Same reportlab-overlay technique as
    # closing date and the page-11 address header above.
    # TREC page 2 of 10 = final PDF page index 2 (cover=0, TREC page 1=idx 1).
    if parsed.get("inspection_days") is not None:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas as rl_canvas

        option_page = final_writer.pages[2]
        overlay_buf = io.BytesIO()
        c = rl_canvas.Canvas(overlay_buf, pagesize=letter)
        c.setFont("Helvetica", 10)
        # Blank starts at x=75.6 (top-down y 284.5-296.6); baseline just
        # above the bottom of that text line, 792 - 296.6 = 495.4.
        c.drawString(82, 496, str(parsed["inspection_days"]))
        c.save()
        overlay_buf.seek(0)

        overlay_page = PdfReader(overlay_buf).pages[0]
        option_page.merge_page(overlay_page)

    # TREC 61-0 (Seller's Disclosure About Groundwater and Surface Water
    # Rights) -- new mandatory form referenced by Paragraph 7(I) of the
    # 07-2026 20-19 template above. Always attached (not conditional on a
    # known well/pond, since the parser has no way to detect that from an
    # SMS offer string) with only the address filled in; every substantive
    # question is left blank for the agent/seller, same reasoning as the
    # 40-11 addendum's blank loan terms. Appended here (after the fixed-index
    # overlays, before the cert page) so it doesn't shift any of them.
    water_pdf_bytes = fill_water_disclosure(parsed)
    final_writer.append(PdfReader(io.BytesIO(water_pdf_bytes)))

    # TREC 36-10 (Addendum for Property Subject to Mandatory Membership in a
    # Property Owners Association) -- unlike the Water Disclosure above,
    # this is genuinely conditional: not every property has a mandatory
    # HOA, so it's only attached when the agent's own text says "HOA" (see
    # _parse_has_hoa() in parser.py). Only the address is filled in; every
    # substantive section (fee delivery method, transfer-fee cap, who pays
    # the title company) is left blank for the same reason as everything
    # else this app leaves blank rather than guesses. The Sec 22 addenda
    # checkbox for this addendum is checked above, alongside the other
    # checkbox-setting logic, when this same condition is true.
    if parsed.get("has_hoa"):
        hoa_pdf_bytes = fill_hoa_addendum(parsed)
        final_writer.append(PdfReader(io.BytesIO(hoa_pdf_bytes)))

    # TREC IABS 1-2 (Information About Brokerage Services) -- required
    # disclosure, always attached. Only the agent's own Sales Agent/Associate
    # row and the brokerage name are auto-filled from their saved profile;
    # everything else on the form is left blank. See iabs.py for why.
    iabs_pdf_bytes = fill_iabs(parsed.get('agent', {}))
    final_writer.append(PdfReader(io.BytesIO(iabs_pdf_bytes)))

    # Certification page (final page): light/print mode, same as the cover
    # page, appended last so it doesn't shift any of the fixed page-index
    # overlays above (closing date, page-11 header, option period).
    cert_pdf_bytes = generate_certification_page(parsed, parsed.get('agent', {}), mode="light")
    final_writer.append(PdfReader(io.BytesIO(cert_pdf_bytes)))

    # No footer, page-number stamp, or any other added mark on the actual
    # TREC contract/addendum pages (indices 1+) -- those are promulgated
    # forms and must be reproduced without alteration. Branding and the
    # "Not affiliated with TREC" disclaimer live on the cover page only
    # (cover_page.py), which is our own document, not a TREC form.
    #
    # Version tracking stays invisible: embedded in document metadata only
    # (queryable later if a bug surfaces and affected offers need to be
    # identified), never stamped onto the visible page content.
    final_writer.add_metadata({"/TxtAnOfferGeneratorVersion": GENERATOR_VERSION})

    safe_addr = "".join(ch for ch in (parsed.get("address") or "offer") if ch.isalnum())[:30]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(OUTPUT_DIR, f"TREC20-19_{safe_addr}_{timestamp}.pdf")

    with open(out_path, "wb") as f:
        final_writer.write(f)

    return out_path

def inspect_fields(pdf_path: str = TEMPLATE_PATH):
    """Reproduces the field discovery used to build FIELD_MAP above."""
    reader = PdfReader(pdf_path)
    fields = reader.get_fields()
    if not fields:
        print("No fillable fields found.")
        return
    print(f"{len(fields)} fields found:")
    for name, f in fields.items():
        print(f" {name!r:60} type={f.get('/FT')}")

if __name__ == "__main__":
    sample = {
        "price": 725000,
        "down_payment_pct": 0.03,
        "close_days": 21,
        "address": "123 Main St, Austin, TX",
    }
    path = fill_offer_pdf(sample, "+15125550100")
    print("Wrote:", path)

