"""
pdf_filler.py — fills TREC No. 20-19 (One to Four Family Residential
Contract, Resale) using its real AcroForm fields.
Correction from earlier attempts: the draft copy (20-19_draft_0.pdf,
with visible redlines) reported ZERO fillable fields, so we built a
coordinate-overlay approach. The clean, final published PDF
(20-19_2.pdf) actually HAS 281 real AcroForm fields. Field-based
filling is far more robust than coordinate overlay -- it doesn't break
if TREC nudges spacing in a future revision -- so we use that instead.
Field names below were confirmed by inspecting 20-19_2.pdf directly
(inspect_fields() at the bottom of this file reproduces that check).
TREC's PDF export tool auto-names fields from nearby text, which is
why some are verbose ("Texas known as") and some are generic
("undefined_3") -- that's TREC's export, not a choice we made.
"""
import os
import io
from datetime import datetime, timedelta
from pypdf import PdfReader, PdfWriter
from cover_page import generate_cover_page

TEMPLATE_PATH = os.environ.get("TREC_TEMPLATE_PATH", "20-19_2.pdf")
OUTPUT_DIR = os.environ.get("OFFER_OUTPUT_DIR", "generated_offers")

# Confirmed against 20-19_2.pdf (the clean, final, mandatory-as-of-7/1/2026 form).
# Field names are auto-generated by TREC's PDF tool, so they're verbose.
FIELD_MAP = {
    # Paragraph 2A: Property description
    "address": "Texas known as",
    "city": "Addition City of",
    "county": "County of",

    # Page headers — "Contract Concerning (Address of Property)"
    "addr_of_prop": "Addr of Prop",

    # Paragraph 9A: Closing date
    "closing_date": "A The closing of the sale will be on or before",
    "closing_year_suffix": "20_2",  # The 2-digit year suffix field (form pre-prints "20")

    # Payment structure (Paragraph 3)
    # TREC 20-19 has: 3A (cash portion), 3B (sum of financing), 3C (total sales price)
    # We map: down payment → 3A, loan → 3B, total → 3C
    "down_payment": "undefined_3",  # 3A: Cash portion (down payment)
    "loan_amount": "undefined_4",   # 3B: Sum of all financing
    "sales_price": "undefined_5",   # 3C: Sales Price (total)

    # Earnest Money & Option Fee (Paragraph 5A)
    "earnest_money": "earnest money of",
    "option_fee": "Option Fee in the form of",
    "earnest_to_escrow": "as earnest money to",  # 5A: deliver to (Escrow Agent)

    # Title company / Escrow (Paragraph 6)
    "title_company": "insurance Title Policy issued by",
    "escrow_agent": "Escrow Agent",

    # Checkboxes
    "third_party_financing": "Third Party Financing Addendum",
    "as_is": "1 Buyer accepts the Property As Is",
    "possession_upon_closing": "upon",

    # Selling (buyer's) agent info — the TextAnOffer user
    "agent_broker_firm": "Other Broker Firm",
    "agent_name": "Selling Associates Name",
    "agent_license": "License No",
    "agent_phone": "Phone",
    "agent_email": "Email",
    "agent_email_2": "Selling Associates Email Address",
    "agent_office_address": "Other Brokers Address",
}

def fill_offer_pdf(parsed: dict, agent_phone: str) -> str:
    if not os.path.exists(TEMPLATE_PATH):
        raise FileNotFoundError(
            f"Template not found at {TEMPLATE_PATH}. "
            "Set TREC_TEMPLATE_PATH to the clean, final 20-19 PDF."
        )
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    reader = PdfReader(TEMPLATE_PATH)
    writer = PdfWriter()
    writer.append(reader)
    
    values = {}

    import re

    # Property description (Paragraph 2A)
    # Strip state from address — the form field already says "Texas, known as"
    addr = ""
    if parsed.get("address"):
        addr = re.sub(r',?\s*\b(TX|Texas)\b', '', parsed["address"], flags=re.IGNORECASE).strip(' ,')
        values[FIELD_MAP["address"]] = addr
    if parsed.get("city"):
        values[FIELD_MAP["city"]] = parsed["city"]
    if parsed.get("county"):
        values[FIELD_MAP["county"]] = parsed["county"]

    # Page header: "Contract Concerning (Address of Property)" on all pages
    full_addr = f"{addr}, {parsed.get('city', '')}, TX" if parsed.get("city") else addr
    if full_addr:
        values[FIELD_MAP["addr_of_prop"]] = full_addr

    # Payment structure (Paragraph 3: A, B, C)
    if parsed.get("down_payment_amount") is not None:
        values[FIELD_MAP["down_payment"]] = f"${parsed['down_payment_amount']:,}"
    if parsed.get("loan_amount") is not None:
        values[FIELD_MAP["loan_amount"]] = f"${parsed['loan_amount']:,}"
    if parsed.get("price") is not None:
        values[FIELD_MAP["sales_price"]] = f"${parsed['price']:,}"

    # Checkboxes handled separately (need /AS and /V set to /On)
    checkboxes_to_check = []

    # Check Third Party Financing when there's a loan
    if parsed.get("loan_amount") and parsed["loan_amount"] > 0:
        checkboxes_to_check.append(FIELD_MAP["third_party_financing"])

    # Default: Buyer accepts Property As Is + possession upon closing
    checkboxes_to_check.append(FIELD_MAP["as_is"])
    checkboxes_to_check.append(FIELD_MAP["possession_upon_closing"])

    # Earnest Money & Option Fee (Paragraph 5A)
    if parsed.get("earnest_money") is not None:
        values[FIELD_MAP["earnest_money"]] = f"${parsed['earnest_money']:,}"
    if parsed.get("option_fee") is not None:
        values[FIELD_MAP["option_fee"]] = f"${parsed['option_fee']}"

    # Closing date (Paragraph 9A)
    # TREC form layout: "closing of the sale will be on or before [Month Day,] 20[__]"
    # The "20" is pre-printed on the form; we only fill the date text and 2-digit year
    if parsed.get("close_days") is not None:
        close_dt = datetime.now() + timedelta(days=parsed["close_days"])
        values[FIELD_MAP["closing_date"]] = close_dt.strftime("%B %d,")
        values[FIELD_MAP["closing_year_suffix"]] = close_dt.strftime("%y")

    # Agent/broker info from profile
    agent = parsed.get("agent", {})
    if agent.get("name"):
        values[FIELD_MAP["agent_name"]] = agent["name"]
    if agent.get("license"):
        values[FIELD_MAP["agent_license"]] = agent["license"]
    if agent.get("brokerage"):
        values[FIELD_MAP["agent_broker_firm"]] = agent["brokerage"]
    if agent.get("phone"):
        values[FIELD_MAP["agent_phone"]] = agent["phone"]
    if agent.get("email"):
        values[FIELD_MAP["agent_email"]] = agent["email"]
        values[FIELD_MAP["agent_email_2"]] = agent["email"]

    # Title company → title policy issuer + escrow agent + earnest money delivery
    if agent.get("title_company"):
        values[FIELD_MAP["title_company"]] = agent["title_company"]
        values[FIELD_MAP["earnest_to_escrow"]] = agent["title_company"]
        values[FIELD_MAP["escrow_agent"]] = agent["title_company"]
    
    from pypdf.generic import NameObject, TextStringObject, BooleanObject

    for page in writer.pages:
        writer.update_page_form_field_values(page, values)

    # Handle parent fields with /Kids (closing date)
    # These aren't direct page annotations so update_page_form_field_values misses them.
    # We set /V on both parent and kid, and remove /AP on kid to force regeneration.
    acroform = writer._root_object.get("/AcroForm")
    if hasattr(acroform, 'get_object'):
        acroform = acroform.get_object()
    if acroform and "/Fields" in acroform:
        for field_ref in acroform["/Fields"]:
            field = field_ref.get_object()
            name = str(field.get("/T", ""))
            if name in values and "/Kids" in field:
                field[NameObject("/V")] = TextStringObject(values[name])
                for kid_ref in field["/Kids"]:
                    kid = kid_ref.get_object()
                    kid[NameObject("/V")] = TextStringObject(values[name])
                    if "/AP" in kid:
                        del kid["/AP"]

    # Check checkboxes by setting /V and /AS to /On
    for page in writer.pages:
        if "/Annots" not in page:
            continue
        for annot_ref in page["/Annots"]:
            annot = annot_ref.get_object()
            name = str(annot.get("/T", ""))
            if name in checkboxes_to_check:
                annot[NameObject("/V")] = NameObject("/On")
                annot[NameObject("/AS")] = NameObject("/On")

    # Ensure filled values render even if the PDF viewer doesn't regenerate appearances.
    if acroform is not None:
        acroform[NameObject("/NeedAppearances")] = BooleanObject(True)

    # Write filled TREC form to buffer (preserves AcroForm with field values)
    trec_buf = io.BytesIO()
    writer.write(trec_buf)
    trec_buf.seek(0)

    # Generate premium cover page
    cover_pdf_bytes = generate_cover_page(parsed, parsed.get('agent', {}))

    # Merge: cover page first, then filled TREC form (append preserves AcroForm)
    final_writer = PdfWriter()
    final_writer.append(PdfReader(io.BytesIO(cover_pdf_bytes)))
    final_writer.append(PdfReader(trec_buf))

    safe_addr = "".join(ch for ch in (parsed.get("address") or "offer") if ch.isalnum())[:30]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(OUTPUT_DIR, f"TREC20-19_{safe_addr}_{timestamp}.pdf")

    with open(out_path, "wb") as f:
        final_writer.write(f)

    return out_path

def inspect_fields(pdf_path: str = TEMPLATE_PATH):
    """Reproduces the field discovery used to build FIELD_MAP above."""
    reader = PdfReader(pdf_path)
    fields = reader.get_fields()
    if not fields:
        print("No fillable fields found.")
        return
    print(f"{len(fields)} fields found:")
    for name, f in fields.items():
        print(f" {name!r:60} type={f.get('/FT')}")

if __name__ == "__main__":
    sample = {
        "price": 725000,
        "down_payment_pct": 0.03,
        "close_days": 21,
        "address": "1740 Grand Ave, Austin, TX",
    }
    path = fill_offer_pdf(sample, "+15125550100")
    print("Wrote:", path)

