"""
pdf_filler.py — fills TREC No. 20-19 (One to Four Family Residential
Contract, Resale) using its real AcroForm fields.
Correction from earlier attempts: the draft copy (20-19_draft_0.pdf,
with visible redlines) reported ZERO fillable fields, so we built a
coordinate-overlay approach. The clean, final published PDF
(20-19_2.pdf) actually HAS 281 real AcroForm fields. Field-based
filling is far more robust than coordinate overlay -- it doesn't break
if TREC nudges spacing in a future revision -- so we use that instead.
Field names below were confirmed by inspecting 20-19_2.pdf directly
(inspect_fields() at the bottom of this file reproduces that check).
TREC's PDF export tool auto-names fields from nearby text, which is
why some are verbose ("Texas known as") and some are generic
("undefined_3") -- that's TREC's export, not a choice we made.
"""
import os
import io
from datetime import datetime, timedelta
from pypdf import PdfReader, PdfWriter
from cover_page import generate_cover_page

TEMPLATE_PATH = os.environ.get("TREC_TEMPLATE_PATH", "20-19_2.pdf")
OUTPUT_DIR = os.environ.get("OFFER_OUTPUT_DIR", "generated_offers")

# Confirmed against 20-19_2.pdf (the clean, final, mandatory-as-of-7/1/2026 form).
# Field names are auto-generated by TREC's PDF tool, so they're verbose.
FIELD_MAP = {
    # Paragraph 2A: Property description
    "address": "Texas known as",
    "city": "Addition City of",
    "county": "County of",

    # Paragraph 9A: Closing date
    "closing_date": "A The closing of the sale will be on or before",
    "closing_year_prefix": "20",  # The "20" prefix field
    "closing_year_suffix": "20_2",  # The 2-digit year suffix field

    # Payment structure (Paragraph 3)
    # TREC 20-19 has: 3A (cash portion), 3B (sum of financing), 3C (total sales price)
    # We map: down payment → 3A, loan → 3B, total → 3C
    "down_payment": "undefined_3",  # 3A: Cash portion (down payment)
    "loan_amount": "undefined_4",   # 3B: Sum of all financing
    "sales_price": "undefined_5",   # 3C: Sales Price (total)

    # Earnest Money & Option Fee (Paragraph 4)
    "earnest_money": "earnest money of",
    "option_fee": "Option Fee in the form of",

    # Title company / Escrow (Paragraph 6)
    "title_company": "insurance Title Policy issued by",
    "escrow_agent": "Escrow Agent",

    # Selling (buyer's) agent info — the TextAnOffer user
    "agent_broker_firm": "Other Broker Firm",
    "agent_name": "Selling Associates Name",
    "agent_license": "License No",
    "agent_phone": "Phone",
    "agent_email": "Email",
    "agent_office_address": "Other Brokers Address",
}

def fill_offer_pdf(parsed: dict, agent_phone: str) -> str:
    if not os.path.exists(TEMPLATE_PATH):
        raise FileNotFoundError(
            f"Template not found at {TEMPLATE_PATH}. "
            "Set TREC_TEMPLATE_PATH to the clean, final 20-19 PDF."
        )
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    reader = PdfReader(TEMPLATE_PATH)
    writer = PdfWriter()
    writer.append(reader)
    
    values = {}

    # Property description (Paragraph 2A)
    if parsed.get("address"):
        values[FIELD_MAP["address"]] = parsed["address"]
    if parsed.get("city"):
        values[FIELD_MAP["city"]] = parsed["city"]
    if parsed.get("county"):
        values[FIELD_MAP["county"]] = parsed["county"]

    # Payment structure (Paragraph 3: A, B, C)
    if parsed.get("down_payment_amount") is not None:
        values[FIELD_MAP["down_payment"]] = f"${parsed['down_payment_amount']:,}"
    if parsed.get("loan_amount") is not None:
        values[FIELD_MAP["loan_amount"]] = f"${parsed['loan_amount']:,}"
    if parsed.get("price") is not None:
        values[FIELD_MAP["sales_price"]] = f"${parsed['price']:,}"

    # Earnest Money & Option Fee (Paragraph 4)
    if parsed.get("earnest_money") is not None:
        values[FIELD_MAP["earnest_money"]] = f"${parsed['earnest_money']:,}"
    if parsed.get("option_fee") is not None:
        values[FIELD_MAP["option_fee"]] = f"${parsed['option_fee']}"

    # Closing date (Paragraph 9A)
    # TREC form layout: "closing of the sale will be on or before [Month Day,] 20[__]"
    # Three fields: main date text, "20" prefix, and 2-digit year suffix
    if parsed.get("close_days") is not None:
        close_dt = datetime.now() + timedelta(days=parsed["close_days"])
        values[FIELD_MAP["closing_date"]] = close_dt.strftime("%B %d,")
        values[FIELD_MAP["closing_year_prefix"]] = "20"
        values[FIELD_MAP["closing_year_suffix"]] = close_dt.strftime("%y")

    # Agent/broker info from profile
    agent = parsed.get("agent", {})
    if agent.get("name"):
        values[FIELD_MAP["agent_name"]] = agent["name"]
    if agent.get("license"):
        values[FIELD_MAP["agent_license"]] = agent["license"]
    if agent.get("brokerage"):
        values[FIELD_MAP["agent_broker_firm"]] = agent["brokerage"]
    if agent.get("phone"):
        values[FIELD_MAP["agent_phone"]] = agent["phone"]
    if agent.get("email"):
        values[FIELD_MAP["agent_email"]] = agent["email"]

    # Title company → title policy issuer + escrow agent
    if agent.get("title_company"):
        values[FIELD_MAP["title_company"]] = agent["title_company"]
        values[FIELD_MAP["escrow_agent"]] = agent["title_company"]
    
    for page in writer.pages:
        writer.update_page_form_field_values(page, values)

    # Ensure filled values render even if the PDF viewer doesn't regenerate appearances.
    if writer._root_object.get("/AcroForm") is not None:
        writer._root_object["/AcroForm"][__import__("pypdf").generic.NameObject("/NeedAppearances")] = \
            __import__("pypdf").generic.BooleanObject(True)

    # Generate premium cover page
    cover_pdf_bytes = generate_cover_page(parsed, parsed.get('agent', {}))

    # Merge cover page with TREC form
    cover_reader = PdfReader(io.BytesIO(cover_pdf_bytes))
    final_writer = PdfWriter()

    # Add cover page first
    final_writer.add_page(cover_reader.pages[0])

    # Then add all TREC form pages
    for page in writer.pages:
        final_writer.add_page(page)

    safe_addr = "".join(ch for ch in (parsed.get("address") or "offer") if ch.isalnum())[:30]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(OUTPUT_DIR, f"TREC20-19_{safe_addr}_{timestamp}.pdf")

    with open(out_path, "wb") as f:
        final_writer.write(f)

    return out_path

def inspect_fields(pdf_path: str = TEMPLATE_PATH):
    """Reproduces the field discovery used to build FIELD_MAP above."""
    reader = PdfReader(pdf_path)
    fields = reader.get_fields()
    if not fields:
        print("No fillable fields found.")
        return
    print(f"{len(fields)} fields found:")
    for name, f in fields.items():
        print(f" {name!r:60} type={f.get('/FT')}")

if __name__ == "__main__":
    sample = {
        "price": 725000,
        "down_payment_pct": 0.03,
        "close_days": 21,
        "address": "1740 Grand Ave, Austin, TX",
    }
    path = fill_offer_pdf(sample, "+15125550100")
    print("Wrote:", path)

